using Server.Common.Items;

namespace Server.Common.Config;

public class LoginBonusConfig
{
    public required Dictionary<int, GameItem> CalendarBase { get; set; }
    public bool IsCalendarAutoGenerated { get; set; } // TODO
}
