using Server.Common.Items;

namespace Server.Common.Config;

public record LoginBonusConfigSection
{
    public bool IsCalendarAutoGenerated { get; set; } // TODO
    public required Dictionary<int, GameItem> CalendarBase { get; init; } = [];
}
