using Server.Common.Items;

namespace Server.Common.Config;

public record SheetDay
{
    public int Day { get; init; }
    public required List<GameItem> Items { get; init; }
}

public record LoginBonusSheet
{
    public required string Text { get; init; }
    public required string AssetPath { get; init; }
    public required DateTime StartDate { get; init; }
    public required DateTime EndDate { get; init; }
    public required List<SheetDay> Days { get; init; }
}

public record LoginBonusConfigSection
{
    public bool IsCalendarAutoGenerated { get; init; } // TODO
    public List<LoginBonusSheet> Sheets { get; init; } = [];
    public Dictionary<int, GameItem> CalendarBase { get; init; } = [];
}
