LoginBonus:
  CalendarBase:
    1:
      addType: GameCoin
      amount: 250000
    2:
      addType: SocialPoint
      amount: 1000
    3:
      addType: ExchangePoint
      itemId: 2
      amount: 1
    4:
      addType: Unit
      unitId: 382
      amount: 1
    5:
      addType: Loveca
      amount: 2
    6:
      addType: GameCoin
      amount: 50000
    7:
      addType: SocialPoint
      amount: 1000
    8:
      addType: ExchangePoint
      itemId: 2
      amount: 1
    9:
      addType: Unit
      unitId: 382
      amount: 1
    10:
      addType: Loveca
      amount: 2
    11:
      addType: GameCoin
      amount: 50000
    12:
      addType: SocialPoint
      amount: 1000
    13:
      addType: ExchangePoint
      itemId: 2
      amount: 1
    14:
      addType: Unit
      unitId: 382
      amount: 1
    15:
      addType: Loveca
      amount: 2
    16:
      addType: GameCoin
      amount: 50000
    17:
      addType: SocialPoint
      amount: 1000
    18:
      addType: ExchangePoint
      itemId: 2
      amount: 1
    19:
      addType: Unit
      unitId: 382
      amount: 1
    20:
      addType: Loveca
      amount: 2
    21:
      addType: GameCoin
      amount: 50000
    22:
      addType: SocialPoint
      amount: 1000
    23:
      addType: ExchangePoint
      itemId: 2
      amount: 1
    24:
      addType: Unit
      unitId: 382
      amount: 1
    25:
      addType: Loveca
      amount: 2
    26:
      addType: GameCoin
      amount: 50000
    27:
      addType: SocialPoint
      amount: 1000
    28:
      addType: ExchangePoint
      itemId: 2
      amount: 1
    29:
      addType: Unit
      unitId: 382
      amount: 1
    30:
      addType: GameCoin
      amount: 50000
    31:
      addType: Loveca
      amount: 2
  
  TotalLoginBonus:
    1:
      addType: GameCoin
      amount: 10000
    2:
      addType: SocialPoint
      amount: 1000
    3:
      addType: Unit
      unitId: todo
      amount: 1
    10:
      addType: Loveca
      amount: 3
    20:
      addType: Item
      itemId: todo
      amount: 1
    