Server:
  ServerVersion: "59.4"
  XMessageCodeVerificationEnabled: true
  Database: "PostgreSQL" # should have same name as in connection strings
  RsaPrivateKey: # your private key
  ReleaseInfoKeys:
    - id: 1
      key: asdsadasda
    - id: 2
      key: 12345

Kestrel:
  Endpoints:
    Http:
      Url: http://0.0.0.0:5000
    Https:
      Url: http://0.0.0.0:5001

Award:
  UnlockAll: true

Background:
  UnlockAll: true

Live:
  UnlockAll: true

Unit:
  MuseCenterUnitIds: [ 49, 50, 51, 52, 53, 54, 55, 56, 57 ]
  AqoursCenterUnitIds: [ 788, 789, 790, 791, 792, 793, 794, 795, 796 ]

ConnectionStrings:
  PostgreSQL: 12345
